import crypto from 'crypto';

/**
 * Mock bitmap ownership registry
 * In a real implementation, this would interface with a blockchain or decentralized registry
 */
const ownershipRegistry = new Map();

/**
 * Generate a mock Bitcoin address for the landlord
 * @param {string} seed - Vessel seed
 * @returns {string} - Mock Bitcoin address
 */
export function generateLandlordAddress(seed) {
  // Create a deterministic address from the seed
  const hash = crypto.createHash('sha256').update(seed + 'landlord').digest('hex');
  // Mock Bitcoin address format (not a real address)
  return `bc1q${hash.substring(0, 40)}`;
}

/**
 * Check if royalty has been paid for a vessel
 * @param {number} blockHeight - Block height
 * @returns {boolean} - Royalty payment status
 */
export function checkRoyaltyStatus(blockHeight) {
  const key = `block_${blockHeight}`;
  return ownershipRegistry.get(key)?.royaltyPaid || false;
}

/**
 * Mark royalty as paid for a vessel
 * @param {number} blockHeight - Block height
 * @param {string} txHash - Mock transaction hash
 * @returns {object} - Payment record
 */
export function markRoyaltyPaid(blockHeight, txHash = null) {
  const key = `block_${blockHeight}`;
  const timestamp = new Date().toISOString();
  
  if (!txHash) {
    // Generate mock transaction hash
    txHash = crypto.randomBytes(32).toString('hex');
  }

  const record = {
    blockHeight,
    royaltyPaid: true,
    txHash,
    timestamp
  };

  ownershipRegistry.set(key, record);
  return record;
}

/**
 * Get ownership info for a vessel
 * @param {number} blockHeight - Block height
 * @param {string} seed - Vessel seed
 * @returns {object} - Ownership information
 */
export function getOwnershipInfo(blockHeight, seed) {
  const landlordAddress = generateLandlordAddress(seed);
  const royaltyPaid = checkRoyaltyStatus(blockHeight);
  const key = `block_${blockHeight}`;
  const record = ownershipRegistry.get(key);

  return {
    blockHeight,
    landlordAddress,
    royaltyPaid,
    txHash: record?.txHash || null,
    timestamp: record?.timestamp || null
  };
}

/**
 * Calculate royalty amount (mock calculation)
 * @param {number} displacement - Vessel displacement in tonnes
 * @returns {object} - Royalty calculation
 */
export function calculateRoyalty(displacement) {
  // Mock royalty: 0.01 BTC per tonne (completely fictitious)
  const btcPerTonne = 0.01;
  const royaltyBTC = displacement * btcPerTonne;
  
  // Mock BTC to USD rate
  const btcToUSD = 45000;
  const royaltyUSD = royaltyBTC * btcToUSD;

  return {
    btcAmount: parseFloat(royaltyBTC.toFixed(8)),
    usdAmount: parseFloat(royaltyUSD.toFixed(2)),
    displacement
  };
}

/**
 * Generate ownership certificate (mock)
 * @param {object} data - Vessel data
 * @returns {string} - Certificate text
 */
export function generateOwnershipCertificate(data) {
  const ownershipInfo = getOwnershipInfo(data.blockHeight, data.seed);
  const royalty = calculateRoyalty(data.hydrostatics.displacement);

  return `
╔═══════════════════════════════════════════════════════════════╗
║          VESSEL OWNERSHIP CERTIFICATE (MOCK)                  ║
╚═══════════════════════════════════════════════════════════════╝

Certificate ID:     ${data.seed.substring(0, 16)}...
Bitcoin Block:      #${data.blockHeight}
Block Hash:         ${data.blockHash}

VESSEL SPECIFICATIONS
  LOA:              ${data.params.LOA} m
  BOA:              ${data.params.BOA} m
  Displacement:     ${data.hydrostatics.displacement} tonnes

OWNERSHIP INFORMATION
  Landlord Address: ${ownershipInfo.landlordAddress}
  Royalty Status:   ${ownershipInfo.royaltyPaid ? '✓ PAID' : '✗ UNPAID'}
  ${ownershipInfo.royaltyPaid ? `Transaction:      ${ownershipInfo.txHash}` : ''}
  ${ownershipInfo.royaltyPaid ? `Paid On:          ${ownershipInfo.timestamp}` : ''}

ROYALTY CALCULATION
  Rate:             ${royalty.btcAmount} BTC (${royalty.usdAmount} USD)
  Based On:         ${royalty.displacement} tonnes @ 0.01 BTC/tonne

═══════════════════════════════════════════════════════════════

This is a MOCK certificate for demonstration purposes only.
Not valid for actual ownership or royalty claims.

Generated by VesselForge
`;
}
